insert into public.services (category, name_es, name_en, description_es, description_en, price, currency, duration_minutes) values
('barberia', 'Corte clásico', 'Classic haircut', 'Consulta, corte personalizado y acabado según tu tipo de cabello y estilo.', 'Consultation, personalized cut and finish based on your hair type and style.', null, 'USD', 30),
('barberia', 'Fade y diseño', 'Fade and design', 'Degradado de precisión y detalles adaptados al acabado que buscás.', 'Precision fade and details adapted to the finish you want.', null, 'USD', 30),
('barberia', 'Barba y perfilado', 'Beard trim and shaping', 'Contorno, definición y acabado para mantener una barba limpia y equilibrada.', 'Contouring, definition and finishing for a clean, balanced beard.', null, 'USD', 30),
('barberia', 'Combo de corte y barba', 'Haircut and beard combo', 'Corte y barba coordinados para conseguir un resultado completo y coherente.', 'Haircut and beard grooming coordinated for a complete, cohesive result.', null, 'USD', 30),
('barberia', 'Corte femenino', 'Women''s haircut', 'Corte personalizado según el largo, textura y forma que deseás mantener.', 'A personalized cut based on the length, texture and shape you want to maintain.', null, 'USD', 30),
('barberia', 'Coloración', 'Hair color', 'Color adaptado a tu base, largo y resultado deseado. Requiere valoración previa.', 'Color adapted to your base, length and desired result. A prior consultation is required.', null, 'USD', 30),
('barberia', 'Trenzas', 'Braids', 'Diseños de trenzado según el estilo, la cantidad y el largo del cabello.', 'Braided styles based on the design, quantity and hair length.', null, 'USD', 30),
('spa', 'Pedicure en gel', 'Gel pedicure', 'Cuidado completo y acabado duradero en gel.', 'Complete care with a long-lasting gel finish.', 60.0, 'USD', 30),
('spa', 'Manicure en gel', 'Gel manicure', 'Preparación, cuidado y esmaltado en gel.', 'Preparation, nail care and gel polish.', 40.0, 'USD', 30),
('spa', 'Esmaltado en gel', 'Gel polish', 'Color en gel con acabado brillante y uniforme.', 'Gel color with an even, glossy finish.', 25.0, 'USD', 30),
('spa', 'Remover esmaltado en gel', 'Gel polish removal', 'Retiro cuidadoso del esmaltado en gel.', 'Careful removal of existing gel polish.', 15.0, 'USD', 30),
('spa', 'Remover uñas', 'Nail removal', 'Retiro profesional de uñas aplicadas.', 'Professional removal of applied nails.', 50.0, 'USD', 30),
('spa', 'Masaje sueco relajante', 'Swedish relaxing massage', 'Movimientos largos y suaves para favorecer la relajación y la circulación.', 'Long, soft strokes that encourage relaxation and circulation.', 65.0, 'USD', 60),
('spa', 'Masaje de tejido profundo', 'Deep-tissue massage', 'Presión sostenida y movimientos profundos para trabajar capas internas del músculo.', 'Sustained pressure and deep strokes that target inner muscle layers.', 75.0, 'USD', 60),
('spa', 'Masaje con bambú', 'Bamboo massage', 'Técnica con bambú para estimular el sistema linfático y favorecer la relajación.', 'Bamboo techniques that stimulate the lymphatic system and encourage relaxation.', 80.0, 'USD', 40),
('spa', 'Reflexología', 'Reflexology', 'Presión localizada en manos y pies para favorecer el bienestar integral.', 'Targeted pressure on hands and feet to support overall well-being.', 75.0, 'USD', 40),
('spa', 'Masaje de piernas', 'Leg massage', 'Presión ligera a moderada para aliviar tensión y dolor muscular.', 'Light to moderate pressure to ease tension and muscle discomfort.', 65.0, 'USD', 40),
('spa', 'Masaje Bali para dos', 'Two-therapist Bali massage', 'Dos terapeutas trabajan de forma sincronizada para una experiencia profunda.', 'Two therapists work in sync for a deep, immersive experience.', 150.0, 'USD', 40),
('spa', 'Masaje de espalda', 'Back massage', 'Trabajo concentrado en espalda y cuello para aliviar molestias recurrentes.', 'Focused work on the back and neck to ease recurring discomfort.', 75.0, 'USD', 40),
('spa', 'Masaje tailandés', 'Thai massage', 'Presión, estiramientos asistidos y movilidad en una sesión completa.', 'Pressure, assisted stretching and mobility in a complete session.', 150.0, 'USD', 60),
('spa', 'Aromaterapia', 'Aromatherapy massage', 'Masaje con aceites esenciales para una experiencia sensorial relajante.', 'Massage with essential oils for a relaxing sensory experience.', 75.0, 'USD', 35),
('spa', 'Masaje con piedras calientes', 'Hot-stone massage', 'Calor terapéutico y masaje para relajar músculos y liberar tensión.', 'Therapeutic heat and massage to relax muscles and release tension.', 100.0, 'USD', 40),
('spa', 'Depilación de pierna completa', 'Full-leg waxing', null, null, 50.0, 'USD', 30),
('spa', 'Depilación de media pierna', 'Half-leg waxing', null, null, 25.0, 'USD', 30),
('spa', 'Depilación de espalda completa', 'Full-back waxing', null, null, 45.0, 'USD', 30),
('spa', 'Depilación de pecho completo', 'Full-chest waxing', null, null, 45.0, 'USD', 30),
('spa', 'Depilación de brazo completo', 'Full-arm waxing', null, null, 35.0, 'USD', 30),
('spa', 'Depilación de medio brazo', 'Half-arm waxing', null, null, 25.0, 'USD', 30),
('spa', 'Depilación de línea del bikini', 'Bikini-line waxing', null, null, 35.0, 'USD', 30),
('spa', 'Depilación de axilas', 'Underarm waxing', null, null, 20.0, 'USD', 30),
('spa', 'Depilación de bigote', 'Upper-lip waxing', null, null, 20.0, 'USD', 30),
('spa', 'Diseño de cejas', 'Eyebrow waxing', null, null, 15.0, 'USD', 30),
('spa', 'Depilación facial', 'Face waxing', null, null, 30.0, 'USD', 30),
('spa', 'Depilación de barbilla', 'Chin waxing', null, null, 20.0, 'USD', 30),
('spa', 'Depilación de patillas', 'Sideburn waxing', null, null, 25.0, 'USD', 30),
('spa', 'Exfoliación corporal de café de Costa Rica', 'Costa Rican coffee body scrub', 'Café y miel trabajan la textura de la piel, apoyan la exfoliación y dejan una sensación renovada.', 'Coffee and honey refine skin texture, support exfoliation and leave a renewed feeling.', 55.0, 'USD', 40);
